<?php

class tcBillboardTickets extends Tickets
{
    protected $classKey = 'TicketFile';
    protected $class = 'Ticket';


//    function __construct(modX $modx, array $config = array())
//    {
//        $this->modx->lexicon->load('tcbillboard:default');
//        parent::__construct($modx, $config);
//    }


    /**
     * @param $data
     * @param string $class
     * @return array|string
     */
    public function fileUpload($data, $class = 'Ticket')
    {
        $this->modx->lexicon->load('tcbillboard:default');
        $filesLimit = $this->modx->getOption('tcbillboard_files_limit', null, 12);

        $where = $this->modx->newQuery($this->classKey, array('class' => $this->class));
        if (!empty($data['tid'])) {
            $where->andCondition(array('parent:IN' => array(0, $data['tid'])));
        } else {
            $where->andCondition(array('parent' => 0));
        }
        $where->andCondition(array('createdby' => $this->modx->user->id));
        $where->andCondition(array('deleted' => 0));
        if ($this->modx->getCount($this->classKey, $where) >= $filesLimit) {
            @unlink($data['tmp_name']);

            return $this->error($this->modx->lexicon('tcbillboard_err_file_upload') . $filesLimit);
        }
        return parent::fileUpload($data, $class = 'Ticket');
    }

    /**
     * @param $id
     * @param string $action
     * @return array|string
     */
    public function fileDelete($id, $action = '')
    {
        if ($action == 'img/restore') {
            $this->modx->lexicon->load('tcbillboard:default');
            $filesLimit = $this->modx->getOption('tcbillboard_files_limit', null, 12);

            if ($file = $this->modx->getObject($this->classKey, (int) $id)) {
                $parent = $file->get('parent');
                $where = $this->modx->newQuery($this->classKey, array('class' => $this->class));
                if (!empty($parent)) {
                    $where->andCondition(array('parent:IN' => array(0, $parent)));
                } else {
                    $where->andCondition(array('parent' => 0));
                }
                $where->andCondition(array('createdby' => $this->modx->user->id));
                $where->andCondition(array('deleted' => 0));
                if ($this->modx->getCount($this->classKey, $where) >= $filesLimit) {

                    return $this->error($this->modx->lexicon('tcbillboard_err_file_upload') . $filesLimit);
                }
            }
        }
        return parent::fileDelete($id); // TODO: Change the autogenerated stub
    }
}