<table class="table tcbillboard-table">
    <tr>
        <td>[[%tcbillboard_front_price_day]]:</td>
        <td>[[+price]]</td>
    </tr>
    <tr>
        <td>[[%tcbillboard_front_price_grace_period]]:</td>
        <td>[[+graceperiodprice]]</td>
    </tr>
    <tr>
        <td>[[%tcbillboard_front_grace_day]]:</td>
        <td>[[+graceDays]]</td>
    </tr>
    <tr>
        <td>[[%tcbillboard_front_just_day]]:</td>
        <td>[[+totalDays]]</td>
    </tr>
    <tr>
        <td>[[%tcbillboard_front_amount_grace_period]]:</td>
        <td>[[+costGrace]]</td>
    </tr>
    [[++tcbillboard_nds_active:is=`1`:then=`
    <tr>
        <td>[[%tcbillboard_front_nds]]:</td>
        <td>[[+nds]]</td>
    </tr>
    `]]
    <tr>
        <th>[[%tcbillboard_front_total]]:</th>
        <th>[[+cost]]</th>
    </tr>
</table>